type Todo {
    id : ID!
    title : String!
}

type TodoInput {
    id : ID!
    title : String!
}

type Query {
    todos : [Todo!]
}

type Mutation {
    addTodo(todo : TodoInput! ):Todo!
    deleteTodo(id : String!):String!
    updateTodo(todo : TodoInput! ): Todo!
}